# Generated by Django 3.1 on 2020-08-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20200820_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='activity.account'),
        ),
    ]
