# Generated by Django 3.1 on 2020-08-21 13:54

import activity.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_investment_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.ImageField(null=True, upload_to=activity.utils.upload_to_storage),
        ),
    ]
